### ISSUE TITLE
Something Wrong !

### ISSUE THREAD

**Issue by sluiz-stf** [codePerfectPlus/Stock-Dashbaord#1]
My dashboard don´t open. What´s the problem? @codePerfectPlus 

##################################
Dash is running on http://0.0.0.0:5000/

WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Serving Flask app 'dashboard'
 * Debug mode: on

**Comment by codeperfectplus** [comment]
Is it solved?
